name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'infra/**'

jobs:
  lint-and-type-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Type Check
        run: yarn check-types

      - name: Run Lint
        run: yarn lint --format json --output-file eslint_report.json

      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_level: error
          eslint_flags: '--format json --output-file eslint_report.json'
