name: Run E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'infra/**'

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: yarn test:e2e
